# tasks file for wordpress
---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: wp-cli.yml
  tags:
    - configuration
    - wordpress
    - wordpress-wp-cli

- include: getsalt.yml
  tags:
    - configuration
    - wordpress
    - wordpress-getsalt

- include: core.yml
  tags:
    - configuration
    - wordpress
    - wordpress-core

- include: configure.yml
  tags:
    - configuration
    - wordpress
    - wordpress-configure

- include: wp-cron.yml
  tags:
    - configuration
    - wordpress
    - wordpress-wp-cron

- include: themes.yml
  tags:
    - configuration
    - wordpress
    - wordpress-themes

- include: plugins.yml
  tags:
    - configuration
    - wordpress
    - wordpress-plugins

- include: users.yml
  tags:
    - configuration
    - wordpress
    - wordpress-users

- include: options.yml
  tags:
    - configuration
    - wordpress
    - wordpress-options

- include: queries.yml
  tags:
    - configuration
    - wordpress
    - wordpress-queries

- include: secure.yml
  tags:
    - configuration
    - wordpress
    - wordpress-secure

- include: optimize.yml
  tags:
    - configuration
    - wordpress
    - wordpress-optimize

- include: chown.yml
  tags:
    - configuration
    - wordpress
    - wordpress-chown
